version: '3.7'

services: 

    github_api_prod:
        container_name: gh_api-prod
        image: gh_api
        build: 
            context: ./api
            dockerfile: Dockerfile
        environment:
            REDIS_URL_NET: redis://redis_prod:6379
            APP_ENV: ${APP_ENV}
            PYTHONPATH: /api/modules
            GITHUB_API: https://api.github.com
            GITHUB_TRENDING_URL: https://github.com/trending
        volumes:
            - ./api:/api
        ports:
            - "5067:2067"
        networks: 
            - web-prod
        depends_on:
            - redis_prod
        entrypoint: 
            - sh
            - /api/entrypoint.sh

    github_web_nginx:
        container_name: gh_client_side-nginx
        image: gh_client_side-nginx
        build: 
            context: ./client
            dockerfile: Dockerfile
        depends_on:
            - github_api_prod
        ports:
            - "80:80"
            # - "443:443"
        volumes:
            - ./client/nginx-conf/nginx.conf:/etc/nginx/nginx.conf
        networks: 
            - web-prod
            - default
    
    redis_prod:
        image: redis:6.0-rc2
        container_name: redis-cache-prod
        command: ["redis-server", "--appendonly", "yes"]
        expose:
            - 6379
        networks: 
            - web-prod
        volumes:
            - redis-data-prod:/data
networks: 
    web-prod:
volumes:
    redis-data-prod:
