version: '3.7'

services: 

    github_api_prod:
        container_name: gh_api-prod
        image: gh_api
        build: 
            context: ./api
            dockerfile: Dockerfile
        environment:
            APP_ENV: production
            PYTHONPATH: /api/modules
            GITHUB_API: https://api.github.com
            GITHUB_TRENDING_URL: https://github.com/trending
            X_GUNICORN_PORT: 2067
        volumes:
            - ./api:/api
        ports:
            - "5067:2067"
        networks: 
            - web-prod
            - redis-net
        depends_on:
            - redis_prod
        entrypoint: 
            - /api/entrypoint.sh

    github_web_nginx:
        container_name: gh_client_side-nginx
        image: gh_client_side-nginx
        build: 
            context: ./client
            dockerfile: Dockerfile
        depends_on:
            - github_api_prod
        ports:
            - "80:80"
            # - "443:443"
        volumes:
            - ./client/nginx-conf/nginx.conf:/etc/nginx/nginx.conf
        networks: 
            - web-prod
    
    redis_prod:
        image: redis:6.0-rc2
        container_name: redis-cache-prod
        entrypoint: /redis-cluster.sh
        depends_on:
            - redis-1
            - redis-2
            - redis-3
            - redis-4
            - redis-5
            - redis-6
        expose:
            - 6379
        networks: 
            redis-net:
                ipv4_address: 10.0.0.2
        volumes:
            - redis-data-prod-cluster:/data
            - ./redis/redis-cluster.sh:/redis-cluster.sh

    redis-1:
        build: 
            context: ./redis
        container_name: redis_1
        image: redis-nodes
        environment:
            _REDIS_PORT: 6380
        expose: 
            - 6380
        networks:
            redis-net:
                ipv4_address: 10.0.0.11
        volumes:
            - ./redis/entrypoint.sh:/source-dir/entrypoint.sh
            - ./redis/redis.conf:/source-dir/template.conf
            - redis-data-prod-1:/data

    redis-2:
        build: 
            context: ./redis
        container_name: redis_2
        image: redis-nodes
        environment:
            _REDIS_PORT: 6381
        expose: 
            - 6381
        networks:
            redis-net:
                ipv4_address: 10.0.0.12
        volumes:
            - ./redis/entrypoint.sh:/source-dir/entrypoint.sh
            - ./redis/redis.conf:/source-dir/template.conf
            - redis-data-prod-2:/data
    
    redis-3:
        build: 
            context: ./redis
        container_name: redis_3
        image: redis-nodes
        environment:
            _REDIS_PORT: 6382
        expose: 
            - 6382
        networks:
            redis-net:
                ipv4_address: 10.0.0.13
        volumes:
            - ./redis/entrypoint.sh:/source-dir/entrypoint.sh
            - ./redis/redis.conf:/source-dir/template.conf
            - redis-data-prod-3:/data
    
    redis-4:
        build: 
            context: ./redis
        container_name: redis_4
        image: redis-nodes
        environment:
            _REDIS_PORT: 6383
        expose: 
            - 6383
        networks:
            redis-net:
                ipv4_address: 10.0.0.14
        volumes:
            - ./redis/entrypoint.sh:/source-dir/entrypoint.sh
            - ./redis/redis.conf:/source-dir/template.conf
            - redis-data-prod-4:/data
    
    redis-5:
        build: 
            context: ./redis
        container_name: redis_5
        image: redis-nodes
        environment:
            _REDIS_PORT: 6384
        expose: 
            - 6384
        networks:
            redis-net:
                ipv4_address: 10.0.0.15
        volumes:
            - ./redis/entrypoint.sh:/source-dir/entrypoint.sh
            - ./redis/redis.conf:/source-dir/template.conf
            - redis-data-prod-5:/data

    redis-6:
        build: 
            context: ./redis
        container_name: redis_6
        image: redis-nodes
        environment:
            _REDIS_PORT: 6385
        expose: 
            - 6385
        networks:
            redis-net:
                ipv4_address: 10.0.0.16
        volumes:
            - ./redis/entrypoint.sh:/source-dir/entrypoint.sh
            - ./redis/redis.conf:/source-dir/template.conf
            - redis-data-prod-6:/data
    
    
networks: 
    web-prod:
    redis-net:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/16
volumes:
    redis-data-prod-1:
    redis-data-prod-2:
    redis-data-prod-3:
    redis-data-prod-4:
    redis-data-prod-5:
    redis-data-prod-6:
    redis-data-prod-cluster: