version: 2.1

jobs:

  build:
    working_directory: ~/github-api-client
    docker:
      - image: circleci/python:3.7-buster
        environment:
          PYTHONPATH: /home/circleci/github-api-client/api/modules
          GITHUB_API: https://api.github.com
          GITHUB_TRENDING_URL: https://github.com/trending
          LANG: en_US.UTF-8
    steps:
      - checkout
      - run:
          working_directory: ./api
          command: |
            pip install --upgrade pip
            pip install pipenv
            pipenv lock --clear
            pipenv install --system --deploy --ignore-pipfile --skip-lock --verbose
      - run:
          command: | 
            sudo apt-get update 
            sudo DEBIAN_FRONTEND=noninteractive apt-get install -y locales
      - run:
          command: |
            sudo sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
            sudo dpkg-reconfigure --frontend=noninteractive locales
            sudo update-locale LANG=en_US.UTF-8
      - run:
          working_directory: ./api
          command: |
            sh run_tests.sh
